[project]
name = "mattsbackend"
version = "0.0.1"
description = "A custom build backend example"

[build-system]
requires = ["setuptools", "wheel", "mattsbackend"]
build-backend = "mattsbackend.build"