name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/project/awesome_requests 
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel build 

      - name: Setup stuff
        run: |
          python - << 'EOF'
          import tomllib, pathlib
          text = pathlib.Path("awesome_requests/pyproject.toml").read_text()
          data = tomllib.loads(text)

          if "dependencies =" in text:
            text = text.replace(
                "dependencies = [",
                "dependencies = [\"mattyt\",",
                1
            )
          else:
            raise RuntimeError("No dependencies array found")

          tomllib.loads(text)

          pathlib.Path("awesome_requests/pyproject.toml").write_text(text)
          EOF

      - name: Upload pyproject.toml as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyproject-toml-result-ci
          path: awesome_requests/pyproject.toml
            
      # Note: that the build step could be insecure (exfiltration of secrets, ...)
      - name: Build package
        run: |
          cd awesome_requests
          # Build using PEP 517 backend configured by pyproject.toml
          python -m build --sdist --wheel

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1